project:
  type: book
  output-dir: docs

book:
  title: "R Avanzado"
  reader-mode: true

  page-footer:
    left: |
      <b>"R Avanzado"</b> fue escrito por Hadley Wickham.
    right: |
      Este libro fue creado usando <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png

  author:
    - name: Hadley Wickham
  search: true
  downloads: [pdf]
  sidebar:
    pinned: true
    tools:
      - icon: github
        menu:
          - text: Original
            url: https://github.com/hadley/adv-r
          - text: Traducci贸n
            url: https://github.com/davidrsch/adv-res
  page-navigation: true
  chapters:
    - index.qmd
    - Preface.qmd
    - Introduction.qmd
    - part: "Fundamentos"
      chapters:
        - Foundations.qmd
        - Names-values.qmd
        - Vectors.qmd
        - Subsetting.qmd
        - Control-flow.qmd
        - Functions.qmd
        - Environments.qmd
        - Conditions.qmd
    - part: "Programaci贸n funcional"
      chapters:
        - FP.qmd
        - Functionals.qmd
        - Function-factories.qmd
        - Function-operators.qmd
    - part: "Programaci贸n orientada a objetos"
      chapters:
        - OO.qmd
        - base-types.qmd
        - S3.qmd
        - R6.qmd
        - S4.qmd
        - OO-tradeoffs.qmd
    - part: "Metaprogramaci贸n"
      chapters:
        - Meta.qmd
        - Big-picture.qmd
        - Expressions.qmd
        - Quotation.qmd
        - Evaluation.qmd
        - Translation.qmd
    - part: "Tecnicas"
      chapters:
        - Techniques.qmd
        - Debugging.qmd
        - Perf-measure.qmd
        - Perf-improve.qmd
        - Rcpp.qmd
    - References.qmd

bibliography: book.bib

format:
  html:
    include-after-body: [ddrsch_script.html]
    css: adv-r.css
    lang:
      es

  pdf:
    documentclass: scrbook
    include_in_header: latex/preamble.tex
    include_before_body: latex/before_body.tex
    include_after_body: latex/after_body.tex
    keep_tex: true
    dev: "cairo_pdf"
    latex_engine: xelatex
    citation_package: natbib
    pandoc_args: ["--top-level-division=chapter", "--lua-filter=latex/sidebar.lua"]
    theme: null
    quote_footer: ["\\hspace*{\\fill} ", ""]
    toc_unnumbered: false
    number_sections: true

editor: visual

