# Introducción {#sec-foundations-intro .unnumbered}

Para comenzar su viaje en el dominio de R, los siguientes siete capítulos lo ayudarán a aprender los componentes básicos de R. Espero que ya haya visto muchas de estas piezas antes, pero probablemente no las haya estudiado en profundidad. Para ayudarlo a verificar su conocimiento actual, cada capítulo comienza con un cuestionario; Si responde correctamente todas las preguntas, ¡siéntase libre de pasar al siguiente capítulo!

1.  El @sec-names-values le enseña sobre una distinción importante en la que probablemente no ha pensado profundamente: la diferencia entre un objeto y su nombre. Mejorar su modelo mental aquí lo ayudará a hacer mejores predicciones sobre cuándo R copia los datos y, por lo tanto, qué operaciones básicas son baratas y cuáles son caras.

2.  El @sec-vectors-chap se sumerge en los detalles de los vectores, ayudándole a aprender cómo encajan los diferentes tipos de vectores. También aprenderá sobre los atributos, que le permiten almacenar metadatos arbitrarios y forman la base de dos de los juegos de herramientas de programación orientada a objetos de R.

3.  El @sec-subsetting describe cómo usar subsetting para escribir código R claro, conciso y eficiente. Comprender los componentes fundamentales le permitirá resolver nuevos problemas al combinar los componentes básicos de formas novedosas.

4.  El @sec-control-flow presenta herramientas de control de flujo que le permiten ejecutar código solo bajo ciertas condiciones, o ejecutar código repetidamente con entradas cambiantes. Estos incluyen las construcciones importantes `if` y `for`, así como herramientas relacionadas como `switch()` y `while`.

5.  El @sec-functions trata sobre las funciones, los bloques de construcción más importantes del código R. Aprenderá exactamente cómo funcionan, incluidas las reglas de scooping, que rigen cómo R busca valores de nombres. También aprenderá más sobre los detalles detrás de la evaluación diferida y cómo puede controlar lo que sucede cuando sale de una función.

6.  El @sec-environments describe una estructura de datos que es crucial para entender cómo funciona R, pero poco importante para el análisis de datos: el entorno. Los entornos son la estructura de datos que vincula los nombres a los valores y potencian herramientas importantes como los espacios de nombres de paquetes. A diferencia de la mayoría de los lenguajes de programación, los entornos en R son de "primera clase", lo que significa que puede manipularlos como cualquier otro objeto.

7.  El @sec-conditions concluye los fundamentos de R con una exploración de "condiciones", el término genérico que se usa para describir errores, advertencias y mensajes. Seguramente los ha encontrado antes, por lo que en este capítulo aprenderá cómo señalarlos apropiadamente en sus propias funciones y cómo manejarlos cuando se les indique en otro lugar.
